### ISSUE TITLE
Bluetooth HD audio disabled

### ISSUE THREAD

**Issue by selamba** [PotatoDevices/device_xiaomi_lavender#1]
Potato version: 4.1.4

OS doesn't support higher quality Bluetooth audio in 4.1.X (several versions now). There was no such issue in 4.0.X.

When connecting to a Bluetooth speaker, the codec selected is SBC, and aptX is greyed out. Also, the "HD audio" toggle is greyed out too. Tested on a speaker and a pair of headphones, both of which support aptX and worked perfectly on prior versions of potato. Other devices have no issues with said speaker and headphones.

**Comment by etahamad** [comment]
Known issue, `libaptX` and `libaptXHD` need to be updated and moved to system_ext

**Comment by SahilSonar** [comment]
Move wen xD

**Comment by etahamad** [comment]
> Move wen xD

i checked sdm660 team, aptxhd is only supported by QTI BT, not aosp

**Comment by etahamad** [comment]
![Screenshot_20210506-085906](https://user-images.githubusercontent.com/53538887/117254969-6416e600-ae49-11eb-8b01-92fd1e89d7ad.png)
it should be fixed by the next release.
